{{- if .Values.loki.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.namePrefix }}loki-stack
  namespace: argocd
spec:
  project: {{ .Values.global.project }}
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.10.2  # Specify the version of the grafana-operator chart
    chart: loki-stack
    helm:
      values: |
        test_pod:
          enabled: false
          image: bats/bats:1.8.2
          pullPolicy: IfNotPresent
        loki:
          enabled: true
          isDefault: true       
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
          livenessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
          datasource:
            jsonData: "{}"
            uid: ""  

        promtail:
          enabled: true
          config:
            logLevel: info
            serverPort: 3101
            clients:
              - url: http://std-practice-loki-stack:3100/loki/api/v1/push
            positions:
              filename: /var/log/positions.yaml
            scrape_configs:
              - job_name: "kind-audit-logs"
                static_configs:
                  - targets:
                      - localhost
                    labels:
                      job: "kind-audit-logs"
                      __path__: /var/log/kubernetes/kube-apiserver-audit.log    
        fluent-bit:
          enabled: true    
  destination:
    server: {{ .Values.global.clusterEndPoint }}
    namespace: {{ .Values.global.destNamespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  
      - "ServerSideApply=true"          
{{- end }}
