{{- if .Values.loki.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.namePrefix }}loki-stack
  namespace: argocd
spec:
  project: {{ .Values.global.project }}
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.10.2  # Specify the version of the grafana-operator chart
    chart: loki-stack
    helm:
      values: |
        test_pod:
          enabled: false
          image: bats/bats:1.8.2
          pullPolicy: IfNotPresent
        loki:
          enabled: true
          isDefault: true       
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
          livenessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
          datasource:
            jsonData: "{}"
            uid: ""  
        promtail:
          enabled: true
          config:
            scrape_configs:
                  - job_name: eks-audit-logs
                    aws_sd_configs:
                      - role_arn: arn:aws:iam::637423592422:role/promtail
                        region: ap-south-1
                    relabel_configs:
                      - source_labels: [__meta_aws_log_group_name]
                        regex: "/aws/eks/eks-monitoring-cluster/cluster"
                        action: keep
                      - source_labels: [__meta_aws_log_stream_name]
                        target_label: log_stream
                    labels:
                      job: eks-audit-logs
              
  
        fluent-bit:
          enabled: true    
  destination:
    server: {{ .Values.global.clusterEndPoint }}
    namespace: {{ .Values.global.destNamespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  
      - "ServerSideApply=true"          
{{- end }}
