# kong-values.yaml
admin:
  enabled: true
  http:
    enabled: true

manager:
  enabled: true
  ingress:
    enabled: true
    hostname: kong-manager.localhost
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
    # tls: []
    path: /
  http:
    enabled: true

env:
  admin_gui_auth: basic-auth
  admin_gui_session_conf: |
    {"secret":"super_secret_session_key", "cookie_secure": false}

proxy:
  type: LoadBalancer
  http:
    enabled: true

ingressController:
  installCRDs: false
