apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- toYaml .Values.ingress.annotations | indent 4 }}
  labels:
    {{- toYaml .Values.ingress.labels | indent 4 }}
  name: {{ template "fullname" . }}-socks-ingress
spec:
  rules:
  - host: {{ .Values.ingress.host }}  # Moved the host field outside of paths
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front-end
            port:
              number: 80
  {{- if .Values.ingress.tlsSecretName }} # Only include TLS configuration if specified
  tls:
  - secretName: {{ .Values.ingress.tlsSecretName }}
    hosts:
    - {{ .Values.ingress.host }}
  {{- end }}
