apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prom
  namespace: utilities
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 58.6.0          
    chart: kube-prometheus-stack    
    helm:
      valueFiles:
        - prom-values.yaml    
  destination:
    server: https://kubernetes.default.svc
    namespace: utilities
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true