apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prom-app
  namespace: utilities
spec:
  project: default
  source:
    path: applications/utility/prom
    repoURL: git@github.com:argadepp/argocd-demo.git
    targetRevision: master
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2