server:
  image:
    repository: prom/prometheus
    tag: v2.54.1
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - prometheus.localhost
    paths:
      - /
  service:
    type: ClusterIP

alertmanager:

pushgateway:

nodeExporter:

kubeStateMetrics:

# Disable persistent volumes for KIND (optional)
serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
