users:
  - name: "pratik-argade"
    namespace: "utilities"
    role: "admin"
  - name: "vishal-bobade"
    namespace: "utilities"
    role: "view"
  - name: "ruturaj-kadikar"
    namespace: "utilities"
    role: "edit"
