namePrefix: std-practice-ds-
grafanaInstance: std-practice-grafana-operator
datasources:
  - name: loki
    type: loki
    url: http://loki-app.utilities.svc.cluster.local:3100
    access: proxy
    jsonData:
      tlsSkipVerify: true
      timeInterval: "5s"
    namespace: utilities  
  - name: prometheus
    type: prometheus
    url: http://prometheus.utilities.svc.cluster.local:9090
    access: proxy
    jsonData:
      tlsSkipVerify: true
    namespace: utilities   
