apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 4.7.2  # Specify the version of the grafana-operator chart
    chart: grafana-operator
    helm:
      values: |
        ## Minimal Helm values ##
        global:       
        operator:
          enabled: true
          image:
            registry: docker.io
            repository: bitnami/grafana-operator
            tag: 5.13.0-debian-12-r0
            digest: ""
        grafana:
          enabled: true
          image:
            registry: docker.io
            repository: bitnami/grafana
            tag: 11.2.0-debian-12-r3
            digest: ""
          ingress:
            enabled: true
            ingressClassName: "nginx"
            host: grafana.localhost
            path: /
          persistence:
            enabled: true
            size: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: utilities
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  
      - "ServerSideApply=true"          