apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: loki
  namespace: utilities
spec:
  instanceSelector:
    matchLabels:
      app.kubernetes.io/instance: "grafana-operator"
  datasource:
    name: loki
    type: loki
    access: proxy
    url: http://loki-app.utilities.svc.cluster.local:3100
    jsonData:
      "tlsSkipVerify": true
      "timeInterval": "5s"