apiVersion: v1
kind: Secret
metadata:
  name: mimir-aws-credentials
  namespace: utilities
type: Opaque
data:
  access_key_id: <BASE64_ENCODED_AWS_ACCESS_KEY>
  secret_access_key: <BASE64_ENCODED_AWS_SECRET_KEY>
