---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: utilities
  labels:
    app: promtail
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      containers:
        - name: promtail
          image: grafana/promtail:latest
          args:
            - -config.file=/etc/promtail/promtail-config.yaml
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: tmpkubernetes
              mountPath: /tmp/kubernetes
              readOnly: false
      volumes:
        - name: config
          configMap:
            name: promtail-config
        - name: tmpkubernetes
          hostPath:
            path: /tmp/kubernetes
            type: DirectoryOrCreate
  


