apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prom
  namespace: utilities
spec:
  instanceSelector:
    matchLabels:
      app.kubernetes.io/instance: "grafana-operator"
  datasource:
    name: prom
    type: prometheus
    access: proxy
    url: http://prometheus-operated.utilities.svc.cluster.local:9090
    isDefault: true
    jsonData:
      "tlsSkipVerify": true
      "timeInterval": "5s"