apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: utilities
data:
  promtail-config.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    clients:
      - url: http://std-practice-loki-stack:3100/loki/api/v1/push

    positions:
      filename: /tmp/positions.yaml

    scrape_configs:
      - job_name: system
        static_configs:
          - targets:
              - localhost
            labels:
              job: varlogs
              __path__: /tmp/kubernetes

      - job_name: kube_audit_logs
        static_configs:
          - targets:
              - localhost
            labels:
              job: kube_audit
              __path__: /tmp/kubernetes
