apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prom-ds
  namespace: utilities
spec:
  instanceSelector:
    matchLabels:
      app.kubernetes.io/instance: std-practice-grafana-operator
  datasource:
    name: prom
    type: prometheus
    access: proxy
    url: http://prometheus-operated.utilities.svc.cluster.local:9090
    jsonData:
      "tlsSkipVerify": false
      "timeInterval": "5s"
