---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pratik-argade
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-deleter
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pratik-argade-pod-deleter
  namespace: default
subjects:
- kind: ServiceAccount
  name: pratik-argade
  namespace: default
roleRef:
  kind: Role
  name: pod-deleter
  apiGroup: rbac.authorization.k8s.io

