---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pratik-argade
  namespace: utilities

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-manager
  namespace: utilities
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - update
  - apiGroups: [""]
    resources:
      - configmaps
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-manager-binding
  namespace: utilities
subjects:
  - kind: ServiceAccount
    name: pratik-argade
    namespace: utilities
roleRef:
  kind: Role
  name: pod-manager
  apiGroup: rbac.authorization.k8s.io


