{{- range .Values.users }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .name }}-rolebinding
  namespace: {{ .namespace }}
subjects:
  - kind: User
    name: {{ .name }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: {{ .name }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
