{{- range .Values.datasources }}
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: {{ $.Values.global.namePrefix }}{{ .name }}
  namespace: {{ .namespace }}
spec:
  instanceSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ $.Values.global.grafanaInstance }}
  datasource:
    name: {{ .name }}
    type: {{ .type }}
    access: {{ .access }}
    url: {{ .url }}
    jsonData:
      {{- range $key, $value := .jsonData }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
{{- end }}
