apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-test-script
  namespace: default
data:
  test.js: |
    import http from 'k6/http';
    import { check, sleep } from 'k6';

    export let options = {
      vus: 10, // Number of virtual users
      duration: '30s', // Duration of the test
    };

    export default function () {
      let res = http.get('http://nginx-service.default.svc.cluster.local');
      check(res, {
        'is status 200': (r) => r.status === 200,
      });
      sleep(1);
    }
---
apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6-test
  namespace: default
spec:
  parallelism: 5
  script:
    configMap:
      name: k6-test-script
  arguments: --out influxdb=http://influxdb.utilities.svc.cluster.local:8086/k6
