apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-test-script
  namespace: default
data:
  test.js: |
    import http from 'k6/http';
    import { check, sleep } from 'k6';

    export let options = {
      vus: 10, // Number of virtual users
      duration: '30s', // Duration of the test
    };

    export default function () {
      let res = http.get('http://nginx-service.default.svc.cluster.local');
      check(res, {
        'is status 200': (r) => r.status === 200,
      });
      sleep(1);
    }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: k6-load-test
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: k6
        image: grafana/k6:latest
        args:
        - run
        - --out
        - influxdb=http://influxdb.utilities.svc.cluster.local:8086
        - /test/test.js
        volumeMounts:
        - name: k6-test-script
          mountPath: /test
      restartPolicy: Never
      volumes:
      - name: k6-test-script
        configMap:
          name: k6-test-script
  backoffLimit: 1
