apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.10.2  # Specify the version of the grafana-operator chart
    chart: loki-stack
    helm:
      values: |
        test_pod:
          enabled: false
          image: bats/bats:1.8.2
          pullPolicy: IfNotPresent
        loki:
          enabled: true
          isDefault: true
          url: http://{{(include "loki.serviceName" .)}}:{{ .Values.loki.service.port }}
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
          livenessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
          datasource:
            jsonData: "{}"
            uid: ""  
        fluent-bit:
          enabled: true    
  destination:
    server: https://kubernetes.default.svc
    namespace: utilities
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  
      - "ServerSideApply=true"          