apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: std-practice-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argadepp.github.io/helm-chart/
    chart: monitoring          # 👈 chart name from your Chart.yaml
    targetRevision: 0.1.0      # 👈 chart version
    helm:
      values: |
        ## Minimal Helm values ##        
        global:
          destNamespace: utilities
          clusterEndPoint: https://kubernetes.default.svc
          project: default
        
        namePrefix: std-practice-
        grafanaOperator:
          enabled: false
          repoURL: https://charts.bitnami.com/bitnami
          targetRevision: 4.7.2
          chart: grafana-operator
          operatorImageTag: 5.13.0-debian-12-r0
          grafanaImageTag: 11.2.0-debian-12-r3
          ingressHost: windows.local
          persistenceSize: 1Gi
          
        grafanaMimir:
          enabled: false
          repoURL: https://grafana.github.io/helm-charts
          targetRevision: 5.5.0 
          chart: mimir-distributed        
        
        loki:
          enabled: true
          
        prom: 
          enabled: true    
          ingressHost: localhost
        
        cloudwatch:
          enabled: false  
        efk: 
          enabled: true  
  destination:
    server: https://kubernetes.default.svc
    namespace: utilities
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  
      - "ServerSideApply=true"
