apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 58.6.0  # Specify the version of kube-prometheus-stack
    chart: kube-prometheus-stack
    helm:
      values: |
        ## Minimal Helm values ##
        grafana:
          enables: false
        alertmanager:
          enables: false  
        prometheus:
          ingress:
            enabled: true
            hosts:
              - prometheus.localhost
          prometheusSpec:
            storageSpec: 
             volumeClaimTemplate:
               spec:
                #  storageClassName: gluster
                 accessModes: ["ReadWriteOnce"]
                 resources:
                   requests:
                     storage: 1Gi    

  destination:
    server: https://kubernetes.default.svc
    namespace: utilities
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true    
      - "ServerSideApply=true"        