apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.14.1 # Specify the version of the grafana-operator chart
    chart: cert-manager
    helm:
      values: |
        installCRDs=true
  destination:
    server: https://kubernetes.default.svc
    namespace: utilities
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  
      - "ServerSideApply=true"          