apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sock-shop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/argadepp/argocd-demo.git
    targetRevision: master # Specify the version of the grafana-operator chart
    path: applications/sockshop
    helm:
      values: |
        istio:
          enabled: true

        ingress:
            annotations:
                kubernetes.io/ingress.class: nginx
            labels: {}
            host: 'shop.localhost'
            tlsSecretName: ''
  destination:
    server: https://kubernetes.default.svc
    namespace: utilities
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  
      - "ServerSideApply=true"          