apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: truedesk-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argadepp.github.io/helm-chart/
    targetRevision: 0.1.0
    chart: truedesk
    helm:
      values: |
        ## Minimal Helm values ## 
        # Default values for myapp.
        
        trudesk:
          image:
            repository: polonel/trudesk
            tag: "1"
          replicaCount: 1
          service:
            port: 8118
          ingress:
            enabled: true
            hosts: localhost
            paths:
              - path: /truedesk
                pathType: Prefix
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
          volumes:
            uploads:
              size: 100Mi
            backups:
              size: 100Mi
        
        mongo:
          image:
            repository: mongo
            tag: "5.0-focal"
          replicaCount: 1
          service:
            port: 27017
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
          volumes:
            data:
              size: 100Mi
            db:
              size: 100Mi
        
        elasticsearch:
          image:
            repository: elasticsearch
            tag: "8.0.0"
          replicaCount: 1
          service:
            httpPort: 9200
            transportPort: 9300
          resources:
            requests:
              memory: "100Mi"
              cpu: "500m"
          volumes:
            data:
              size: 100Mi
        
  destination:
    server: https://kubernetes.default.svc
    namespace: hosting
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  
      - "ServerSideApply=true"

